[package]
name = "fortikey"
version = "0.1.0"
edition = "2023_01"

[dependencies]
starknet = "2.11.4"

[tool.starknet.contracts]
fortikey = ["src/lib.cairo"]

[tool.starknet.cairo]
sierra = true
casm = true
